import { useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export default function GeoAnalyticsCard({ summary, hotspots }) {
  const [locationLevel, setLocationLevel] = useState('areas');
  const locationData = (summary?.[locationLevel] || []).slice(0, 8);
  return <section className="geo-analytics-grid">
    <article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Complaints by location</p><h2>Most reported {locationLevel === 'areas' ? 'areas' : 'cities'}</h2></div></div><div className="hotspot-tabs location-level-tabs"><button type="button" className={locationLevel === 'areas' ? 'active' : ''} onClick={() => setLocationLevel('areas')}>Areas</button><button type="button" className={locationLevel === 'cities' ? 'active' : ''} onClick={() => setLocationLevel('cities')}>Cities</button></div><div className="geo-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={locationData} layout="vertical" margin={{ left: 8, right: 12 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey={locationLevel === 'areas' ? 'area' : 'city'} width={95} tick={{ fontSize: 9 }} /><Tooltip /><Bar dataKey="count" name="Complaints" fill="#82a878" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div></article>
    <article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Category distribution</p><h2>Reports by category</h2></div></div><div className="geo-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={(summary?.categories || []).slice(0, 8)}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="category" interval={0} angle={-20} textAnchor="end" height={48} tick={{ fontSize: 8 }} tickFormatter={(value) => value.replaceAll('_', ' ')} /><YAxis allowDecimals={false} tick={{ fontSize: 9 }} /><Tooltip /><Bar dataKey="count" name="Complaints" fill="#d99967" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></article>
    <article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Hotspot trend</p><h2>Monthly hotspots</h2></div></div><div className="geo-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={hotspots?.trend || []}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" tick={{ fontSize: 9 }} /><YAxis allowDecimals={false} tick={{ fontSize: 9 }} /><Tooltip /><Area type="monotone" dataKey="activeHotspots" name="Hotspots" stroke="#be745b" fill="#f1d5c6" /><Area type="monotone" dataKey="complaints" name="Reports" stroke="#82a878" fill="#dcebd6" /></AreaChart></ResponsiveContainer></div></article>
  </section>;
}
